version: '3.8'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  web:
    build: ./project
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    entrypoint: [ "./entrypoint.sh" ]
    command: gunicorn --bind 0.0.0.0:8000 project.wsgi:application

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - mynetwork


networks:
  mynetwork:

volumes:
  static_volume: