# Generated by Django 5.1.3 on 2024-11-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_flaggedmessage_client_msg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="flaggedmessage",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
