# Generated by Django 5.1.3 on 2024-11-06 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_flaggedmessage_is_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaggedmessage",
            name="matched_pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.pattern",
            ),
        ),
    ]
